<%@ Page Language="VB" AutoEventWireup="false" CodeFile="Cart Test.aspx.vb" Inherits="Cart_Test" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <link href="StyleSheet.css" rel="stylesheet" />
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:GridView  ShowFooter="True"  ID="GridView1" runat="server" AutoGenerateColumns="False"
                AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="id"
                Caption="Shopping Cart details" CellSpacing="15" CellPadding="15" FooterStyle-BorderStyle="None" 
                DataSourceID="SqlDataSource1" CssClass="grid">
                <EditRowStyle CssClass="edit" />
                <FooterStyle BorderStyle="None" />
                <HeaderStyle CssClass="header" />
                <Columns>

                    <%-- For ID --%>

                    <asp:TemplateField HeaderText="ID"
                        Visible="False">
                        <EditItemTemplate>
                            <asp:Label ID="Editlbid" runat="server" Text='<%#bind("id") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Itemlbid" runat="server" Text='<%#bind("id") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>


                    <%--For Image--%>
                    <asp:TemplateField HeaderText="Images">
                        <EditItemTemplate>
                            <asp:Image ID="EditImage1" CssClass="cartimg" ImageUrl='<%#bind("img") %>'
                                runat="server" />

                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Image ID="ItemImage1" CssClass="img" ImageUrl='<%#bind("img") %>'
                                runat="server" />
                        </ItemTemplate>
                    </asp:TemplateField>


                    <%-- For Name --%>
                    <asp:TemplateField HeaderText="Name">
                        <EditItemTemplate>
                            <asp:Label ID="Editlbnm" runat="server" Text='<%#bind("nm") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Itemlbnm" runat="server" Text='<%#bind("nm") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>


                    <%-- For Desc --%>
                    <asp:TemplateField HeaderText="Description">
                        <EditItemTemplate>
                            <asp:Label ID="Editlbdesc" runat="server" Text='<%#bind("disc") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Itemlbdesc" runat="server" Text='<%#bind("disc") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>


                    <%-- For Qty --%>

                    <asp:TemplateField HeaderText="Qunatity">
                        <EditItemTemplate>
                            <asp:DropDownList CssClass="drop" AutoPostBack="true" ID="DropDownList1" runat="server">
                                <asp:ListItem Text="1" Value="1"></asp:ListItem>
                                <asp:ListItem Text="2" Value="2"></asp:ListItem>
                                <asp:ListItem Text="3" Value="3"></asp:ListItem>
                                <asp:ListItem Text="4" Value="4"></asp:ListItem>
                                <asp:ListItem Text="5" Value="5"></asp:ListItem>
                                <asp:ListItem Text="6" Value="6"></asp:ListItem>
                                <asp:ListItem Text="7" Value="7"></asp:ListItem>
                                <asp:ListItem Text="8" Value="8"></asp:ListItem>
                                <asp:ListItem Text="9" Value="9"></asp:ListItem>
                                <asp:ListItem Text="10" Value="10"></asp:ListItem>
                            </asp:DropDownList>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Itemlbqty" runat="server" Text='<%#bind("qty") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>


                    <%-- For Price --%>
                                     
                    <asp:TemplateField HeaderText="Price">
                        <EditItemTemplate>
                            <asp:Label ID="Editlbprice" runat="server" Text='<%#bind("price") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Itemlbprice" runat="server" Text='<%#bind("price") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>

                    
                </Columns>
                <FooterStyle CssClass="footer" />
            </asp:GridView>
            <br />
            <br />

            <asp:Button ID="Button1" CssClass="bt" runat="server" Text="Back to Home" />
            <br />
            <br />
            <br />
        </div>
    </form>
</body>
</html>
